version: 3

dotenv: [".env", ".env.local", "{{.ENV}}/.env", "{{.HOME}}/.env"]

tasks:
  default:
    cmds:
      - task --list

  dev:
    desc: "Run application in local development mode"
    cmds:
      - go run *.go
    env:
      INPUT_FILE_NAME: ./examples/infrastructure.yaml
      INPUT_ENVIRONMENT: dev

  docker:build:
    desc: "Build docker image"
    cmds:
      - docker build -t action-iac-generator .

  docker:run:
    desc: "Run docker image"
    cmds:
      - | 
        docker run \
        -it -v ./examples:/examples \
        -e INPUT_FILE_NAME=./examples/infrastructure.yaml \
        -e INPUT_ENVIRONMENT=dev \
        action-iac-generator