version: 3

dotenv: [".env", ".env.local", "{{.ENV}}/.env", "{{.HOME}}/.env"]

tasks:
  default:
    cmds:
      - task --list

  dev:
    desc: "Run application in local development mode"
    cmds:
      - go run *.go
    env:
      INPUT_FILE_NAME: ./examples/infrastructure.yaml